FROM rails
#RUN apt-get update -qq && apt-get install -y build-essential libpq-dev
RUN apt-get update -qq && apt-get install -y vim
RUN  mkdir -p ~/portal
WORKDIR ~/portal
ADD Gemfile Gemfile
ADD Gemfile.lock Gemfile.lock
RUN gem sources --add https://ruby.taobao.org --remove https://rubygems.org/\
RUN bundle config mirror.https://rubygems.org https://ruby.taobao.org
RUN bundle install
ADD . /portal
