# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f72126f06f8e4fa14eca9c53a121d5c64171c4de0a79b42ad5920bc27d7264fb747e5c7bdfac8c8bc9c2a759794cced1281e0c5e7de32345c0ecef55c44c68f4

test:
  secret_key_base: e2e24828dae86ec9f2eed01d57648fa7bdd31563de527afec375286fa000ecf511a02d016d73b282de00faff31c6e1b85d5331512eceb06cd2df5afba8a5db09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
